### ISSUE TITLE
pulp_schedule broken

### ISSUE THREAD

**Issue by ccnifo** [Katello/puppet-pulp#260]
Working on the freshly released 5.0 version, I got an issue with the pulp_schedules stored in my config:
`Error: Could not prefetch pulp_schedule provider 'api': undefined method `each' for nil:NilClass`

The current schedules state cannot be fetched, then the schedules are recreated at each Puppet pass. The only clue I have so far is that it comes from commit 13385b7dbad852be906798ccdeb36a6df749cef6

**Comment by ekohl** [comment]
Thanks! That must have slipped through and I'll have a look. The good news is that 5.0 isn't yet released so only git users are affected.

**Comment by ekohl** [comment]
Since I haven't got a test env with schedules yet, could you try to change the get_repos function in util to:
```ruby
def get_repos(type=nil)
  repos = request_api('/v2/repositories/')
  return repos.select { |repo| repo['notes']['_repo-type'] == type } if type
  repos
end
```

**Comment by ccnifo** [comment]
Better, but still an issue : 
`Error: Could not prefetch pulp_schedule provider 'api': undefined method ``name' for #<Array:0x0000000323a070>`

**Comment by ekohl** [comment]
Looks like ```new()``` in ```self.instances``` also broke it. I've submitted a PR to fix it.
